<!Doctype html>
<html>
	<head>
		<title>{{ html.head.title }}</title>
		<base href="{{ html.head.base_href }}" target="_top" />
		<meta http-equiv="Content-type" content="text/html; charset=utf-8" />
		<meta http-equiv="X-UA-Compatible" content="ie=edge" />
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
		<meta name="robots" content="noindex" />
		<link rel="icon" href="public/images/favicons/favicon.png" />
		<link rel="apple-touch-icon-precomposed" href="rsrc/Dashboard/public/images/favicons/favicon-touch.png" />
		<link rel="stylesheet" href="rsrc/Dashboard/public/css-js/dashboard.css" />
	</head>
	<body>
		<main>
			<div class="jumbotron">
				<div class="container">
					<h1 class="display-3">{{ html.h1 }}</h1>
					<p class="lead">
						Raw denim you probably haven't heard of them jean shorts Austin. Nesciunt tofu stumptown aliqua, retro synth master cleanse. Mustache cliche tempor, williamsburg carles vegan helvetica. Reprehenderit butcher retro keffiyeh dreamcatcher synth. Cosby sweater eu banh mi, qui irure terry richardson ex squid. Aliquip placeat salvia cillum iphone. Seitan aliquip quis cardigan american apparel, butcher voluptate nisi qui.
					</p>
					<hr />
					<p>
						<ul class="nav nav-pills">
							<li class="nav-item">
								<a class="nav-link active" href="#">Active</a>
							</li>
							<li class="nav-item dropdown">
								<a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Dropdown</a>
								<div class="dropdown-menu" x-placement="bottom-start" style="position: absolute; transform: translate3d(0px, 35px, 0px); top: 0px; left: 0px; will-change: transform;">
									<a class="dropdown-item" href="#">Action</a>
									<a class="dropdown-item" href="#">Another action</a>
									<a class="dropdown-item" href="#">Something else here</a>
								<div class="dropdown-divider"></div>
									<a class="dropdown-item" href="#">Separated link</a>
								</div>
							</li>
							<li class="nav-item">
								<a class="nav-link" href="#">Link</a>
							</li>
							<li class="nav-item">
								<a class="nav-link disabled" href="#">Disabled</a>
							</li>
						</ul>
					</p>
				</div>
			</div>
			<div class="container">
				{{ html.content }}
			</div>
		</main>
		<footer class="mt-5">
			<div class="container text-right">
				<p><a href="dashboard?logout=1">@Logout</a></p>
			</div>
		</footer>
		
		<script src="public/css-js/jquery-3.4.1.min.js"></script>
		<script src="public/css-js/popper.min.js"></script>
		<script src="public/css-js/bootstrap.min.js"></script>
		<script src="public/css-js/dashboard.js"></script>
	</body>
</html>